---
title: "OSC_Analysis_CorrectTrials"
author: "Aarthi Ravi"
date: "13/07/2021"
output: html_document
---

```{r setup}
require("knitr")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE)

library(data.table)
library(tidyverse)
library(magrittr)
library(lavaan)
library(car)
library(tidySEM)
library(gridExtra)
library(equatiomatic)
library(psych)
library(gridExtra)
library(ggplot2)
```

# Descriptives/ Preliminary Analyses

```{r data}
data <- read.csv ("OSC_cleaned_ct.csv")
View (data)
data1 <- select (data, ID, AGE,GENDER,BIRTH_EXP,PSYC_DIS,COG_DIS, DIS, PLAY_GAME, REAC_TIME, ACCURACY)
View (data1)
summary (data1)
describe (data1)

d1 <- filter (data1, AGE < 9 )
d2 <- filter (data1, (AGE<12 & AGE>8))
d3 <- filter (data1, AGE>11)
d4 <- filter (data1, GENDER == "male")
d5 <- filter (data1, GENDER == "female")
d6 <- filter (data1, BIRTH_EXP == "V")
d7 <- filter (data1, BIRTH_EXP == "C")
d8 <- filter (data1, PSYC_DIS == "Y")
d9 <- filter (data1, COG_DIS == "Y")
d10 <- filter (data1, DIS == "Y")
d11 <- filter (data1, PLAY_GAME == "Y")


number_group <- c(nrow(d1),nrow(d2),nrow(d3),nrow(d4),nrow(d5),nrow(d6),nrow(d7),
                  nrow(d8),nrow(d9),nrow(d10),nrow(d11))
part_demographics <- data.frame(cbind(nrow(d1),nrow(d2),nrow(d3),nrow(d4),nrow(d5),nrow(d6),nrow(d7),nrow(d8),nrow(d9),nrow(d10),nrow(d11)))

names (part_demographics) <- c("Age_Group1 (6 to 8 yrs)", "Age_Group2 (9 to 11 yrs)", "Age_Group3 (12< yrs)", "Gender_Male","Gender_Female", "Vaginally_born", "C-sec_born", "Psych_Dis", "Cog_dis", "Gen_dis", "Video_gameplay")


kable (part_demographics)
```

# Creating Factors
```{r Factors}
# Creating factors
data1$AGE_GROUPS <- factor(data1$AGE)
data1$AGE_GROUPS <- data1$AGE
data1$AGE_GROUPS[which(data1$AGE < 9)]<- "1"
data1$AGE_GROUPS[which(data1$AGE<12 & data1$AGE>8)]<- "2"
data1$AGE_GROUPS[which(data1$AGE > 11)]<- "3"

data1$AGE_GROUPS <- as.factor (data1$AGE_GROUPS)
data1$BIRTH_EXP <- as.factor (data1$BIRTH_EXP)
data1$GENDER <- as.factor(data1$GENDER)
```

# Data Distribution Plots
```{r plots}
# Normal Distribution

shapiro.test(d2$REAC_TIME)
shapiro.test(d2$AGE)
hist (data1$REAC_TIME)
hist(data1$AGE)

# Boxplot distribution for Age Groups
boxplot (data1$REAC_TIME~data1$AGE)
boxplot (data1$REAC_TIME~data1$AGE_GROUPS)



# Boxplot distribution for Birth Experience Groups
boxplot (data1$REAC_TIME~data1$BIRTH_EXP)
qplot(AGE_GROUPS, REAC_TIME, data=data1, fill = BIRTH_EXP, geom = 'boxplot', main = "Mixed ANOVA", ylab = "REAC_TIME_CT")


# Boxplot distribution for Gender
boxplot (data1$REAC_TIME~data1$GENDER)
```


```{r ANOVA}
model1 <- aov(REAC_TIME~BIRTH_EXP+AGE_GROUPS, data = data1)
summary (model1)
TukeyHSD(model1)

mod1 <- aov (REAC_TIME~BIRTH_EXP*AGE_GROUPS, data= data1)
summary (mod1)
```